
-- MySQL Script generated by MySQL Workbench
-- Sun Nov 13 23:47:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smokeout
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smokeout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smokeout` DEFAULT CHARACTER SET utf8 ;
USE `smokeout` ;

-- -----------------------------------------------------
-- Table `smokeout`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`sexo` (
  `idsexo` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`persona` (
  `idpersona` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nacimiento` DATE NOT NULL,
  `sexo_idsexo` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_sexo_idx` (`sexo_idsexo` ASC) VISIBLE,
  CONSTRAINT `fk_persona_sexo`
    FOREIGN KEY (`sexo_idsexo`)
    REFERENCES `smokeout`.`sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `pass` VARCHAR(45) NOT NULL,
  `persona_idpersona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `smokeout`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`dia` (
  `iddia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cig_consumidos` INT NOT NULL,
  `primer_cigarro` TIME NOT NULL,
  `dinero_gastado` VARCHAR(45) NOT NULL,
  `persona_idpersona` VARCHAR(45) NOT NULL,
  `ultimo_cigarro` TIME NOT NULL,
  PRIMARY KEY (`iddia`),
  INDEX `fk_dia_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_dia_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `smokeout`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`metodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`metodo` (
  `idmetodo` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(45) NOT NULL,
  `informacion` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idmetodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`habitos_iniciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`habitos_iniciales` (
  `idhabitos_iniciales` INT NOT NULL AUTO_INCREMENT,
  `hora_primer_cig` TIME NOT NULL,
  `cig_diarios` INT NOT NULL,
  `persona_idpersona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhabitos_iniciales`),
  INDEX `fk_habitos_iniciales_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_habitos_iniciales_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `smokeout`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smokeout`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smokeout`.`objetivo` (
  `idobjetivo` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(150) NOT NULL,
  `cigarros_propuestos` INT NOT NULL,
  `fecha_propuesta` DATE NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `metodo_idmetodo` INT NOT NULL,
  `status_idstatus` INT NOT NULL,
  `persona_idpersona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idobjetivo`),
  INDEX `fk_objetivo_metodo1_idx` (`metodo_idmetodo` ASC) VISIBLE,
  INDEX `fk_objetivo_status1_idx` (`status_idstatus` ASC) VISIBLE,
  INDEX `fk_objetivo_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_objetivo_metodo1`
    FOREIGN KEY (`metodo_idmetodo`)
    REFERENCES `smokeout`.`metodo` (`idmetodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objetivo_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `smokeout`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objetivo_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `smokeout`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




-- -----------------------------------------------------
-- Inserciones
-- -----------------------------------------------------

insert into sexo values(0, "mujer");
insert into sexo values(1, "hombre");

insert into status(status) values("pendiente");
insert into status(status) values("logrado");
insert into status(status) values("fallado");

insert into metodo(etiqueta, informacion) values("masticar algo", "Dale a tu boca algo que hacer para resistir un antojo de tabaco. Mastica chicle sin azúcar o pastillas. O bien, come zanahorias crudas, frutos secos o semillas de girasol; algo que sea crujiente y satisfactorio.");
insert into metodo(etiqueta, informacion) values("evitar factores desencadenantes", "El deseo por consumir tabaco probablemente sea más fuerte en los lugares en los que fumabas o mascabas tabaco con más frecuencia, como en fiestas y bares, o en los momentos en que te sentías estresado o tomabas café. Averigua cuáles son tus desencadenantes y ten un plan que te permita evitarlos o enfrentarlos sin consumir tabaco.");
insert into metodo(etiqueta, informacion) values("técnicas de relajación", "Fumar puede haber sido tu manera de lidiar con el estrés y luchar contra el antojo de fumar también puede ser estresante. Para reducir el estrés, prueba con técnicas de relajación, como la respiración profunda, la relajación muscular, el yoga, la visualización, los masajes o escuchar música tranquilizadora.");
insert into metodo(etiqueta, informacion) values("Realiza actividad física", "La actividad física puede ayudar a distraerte del antojo de consumir tabaco. Incluso hacer actividad durante un breve período, como subir y bajar corriendo las escaleras varias veces, puede hacer desaparecer este antojo. Sal a caminar o correr.");

insert into persona values("sajo", "Héctor", "Rodríguez", "2005-08-17", 1);
insert into usuario(persona_idpersona, pass) values("sajo","123");
insert into habitos_iniciales(hora_primer_cig, cig_diarios, persona_idpersona) values("23:04",20,"sajo");

insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-01", 11, 21, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-02", 12, 28, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-03", 2, 7, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-04", 7, 42, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-05", 3, 21, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-06", 4, 28, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-09", 1, 7, "Sajo", curtime(), curtime());
insert into dia(fecha, cig_consumidos, dinero_gastado, persona_idpersona, primer_cigarro, ultimo_cigarro) values("2022-11-11", 6, 42, "Sajo", curtime(), curtime());



